parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $dataPath: '%kernel.project_dir%/data'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
